
###Create a Recurring Item
POST {{HostAddress}}/recurring-items/
Content-Type: application/json

{
  "name": "Test Recurring Item",
  "type": 0,
  "amount": {
    "value": 100.00,
    "currencycode": "CAD"
  },
  "startDate": "2025-11-08",
  "endDate": "2025-11-15",
  "frequency": 0
}

###GetRecurringItems
GET {{HostAddress}}/recurring-items/