// <auto-generated />
using System;
using FamGuild.API.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FamGuild.API.Migrations
{
    [DbContext(typeof(FamGuildDbContext))]
    [Migration("20251109013531_CreateDatabase")]
    partial class CreateDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FamGuild.API.Domain.Treasury.RecurringItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RecurringItems");
                });

            modelBuilder.Entity("FamGuild.API.Domain.Treasury.RecurringItem", b =>
                {
                    b.OwnsOne("FamGuild.API.Domain.Treasury.Common.Money", "Amount", b1 =>
                        {
                            b1.Property<Guid>("RecurringItemId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CurrencyCode")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<decimal>("Value")
                                .HasColumnType("numeric");

                            b1.HasKey("RecurringItemId");

                            b1.ToTable("RecurringItems");

                            b1.WithOwner()
                                .HasForeignKey("RecurringItemId");
                        });

                    b.OwnsOne("FamGuild.API.Domain.Treasury.Common.Recurrence", "Recurrence", b1 =>
                        {
                            b1.Property<Guid>("RecurringItemId")
                                .HasColumnType("uuid");

                            b1.Property<DateOnly?>("EndDate")
                                .HasColumnType("date");

                            b1.Property<int>("Frequency")
                                .HasColumnType("integer");

                            b1.Property<DateOnly>("StartDate")
                                .HasColumnType("date");

                            b1.HasKey("RecurringItemId");

                            b1.ToTable("RecurringItems");

                            b1.WithOwner()
                                .HasForeignKey("RecurringItemId");
                        });

                    b.Navigation("Amount")
                        .IsRequired();

                    b.Navigation("Recurrence")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
