
###Create a Recurring Item
POST {{HostAddress}}/recurring-transactions/
Content-Type: application/json

{
  "name": "Test Recurring Item",
  "type": "income",
  "moneyAmount": 100.00,
  "moneyCurrency": "CAD",
  "startDate": "2025-11-08",
  "endDate": "2025-11-15",
  "frequency": "Weekly"
}

###GetRecurringItems
GET {{HostAddress}}/recurring-transactions/

###GetAccountTransactions
GET {{HostAddress}}/account-transactions/?startDate=2025-11-01&endDate=2025-11-30

###CreateAccountTransactions
POST {{HostAddress}}/account-transactions/
Content-Type: application/json

{
  "AccountTransactionsToCreate": [
    {
      "classification": "income",
      "name": "testAccountTransaction",
      "moneyAmount": 100.00,
        "moneyCurrency": "CAD",
      "category": "Unknown",
      "DateOccurred": "2026-01-22T00:00:00",
      "Status": "Confirmed"
    }
  ]
}